# Generated by Django 4.2.2 on 2023-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tyre_company_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
