# Generated by Django 4.2.2 on 2023-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='abc', max_length=300),
        ),
    ]
