# Generated by Django 4.2.2 on 2023-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='company',
            field=models.CharField(max_length=400),
        ),
    ]
