# Generated by Django 4.2.2 on 2023-07-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile_number',
            new_name='customer_mobile_number',
        ),
    ]
