# Generated by Django 4.2.2 on 2023-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_size_depth_order_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='size',
            field=models.TextField(default=53),
        ),
    ]
