# Generated by Django 4.2.2 on 2023-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_tyre_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.TextField(blank=True, default=0),
        ),
    ]
