# Generated by Django 4.2.2 on 2023-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_tyre_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Items',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='size',
            field=models.TextField(default='145/80/12'),
        ),
    ]
