# Generated by Django 4.2.2 on 2023-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
