# Generated by Django 4.2.2 on 2023-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_price',
            field=models.IntegerField(default=1500),
        ),
    ]
