# Generated by Django 4.2.2 on 2023-12-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_order_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='initial_price',
            field=models.IntegerField(default=1500),
        ),
    ]
