# Generated by Django 4.2.2 on 2024-01-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_dailyprofit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyProfit',
        ),
    ]
